
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
install: "-pip install -r requirements.txt"
deploy:
  api_key:
    secure: DHixWk1rNaeOPFym6nbT8tIxufUqgcDft47yaMQOvMWjlDqOUHbapVgJAO/Ek9o+J6zsgVGprlcrBKw/7w/3mhEM5FZuqlx1/M$

script:
pytest --cov-report term-missing --cov=./app/ app/tests/v1/test.py


