language: python
python:
- "3.6"
install: pip install -r requirements.txt

script:
  - pytest --cov-report term-missing --cov=app app/tests/v1/
after_success: coveralls

#safelist
branches:
  only:
    - develop
